server:
  port: 8181
spring:
  application:
    name: vehicle-reservation
  datasource:
    url: jdbc:postgresql://localhost:5432/vehicle_reservation_system
    username: user_reservations_vehicle
    password: admin1234
    driver-class-name: org.postgresql.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      #      ddl-auto: create
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
